//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimaTempoSimples.Infraestructure.Queries {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Insert_Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Insert_Default() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClimaTempoSimples.Infraestructure.Queries.Insert Default", typeof(Insert_Default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- CIDADE --
        ///DECLARE @CityID INT = 2
        ///
        ///-- DIAS --
        ///DECLARE @Today DATETIME = GETDATE();
        ///DECLARE @Day1 DATETIME = @Today;
        ///DECLARE @Day2 DATETIME = DATEADD(DAY, 1, @Today);
        ///DECLARE @Day3 DATETIME = DATEADD(DAY, 2, @Today);
        ///DECLARE @Day4 DATETIME = DATEADD(DAY, 3, @Today);
        ///DECLARE @Day5 DATETIME = DATEADD(DAY, 4, @Today);
        ///DECLARE @Day6 DATETIME = DATEADD(DAY, 5, @Today);
        ///DECLARE @Day7 DATETIME = DATEADD(DAY, 6, @Today);
        ///DECLARE @Day8 DATETIME = DATEADD(DAY, 7, @Today);
        ///
        ///-------------------- GRAMADO [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Gramado {
            get {
                return ResourceManager.GetString("Gramado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- CIDADE --
        ///DECLARE @CityID INT = 5;
        ///
        ///-- DIAS --
        ///DECLARE @Today DATETIME = GETDATE();
        ///DECLARE @Day1 DATETIME = @Today;
        ///DECLARE @Day2 DATETIME = DATEADD(DAY, 1, @Today);
        ///DECLARE @Day3 DATETIME = DATEADD(DAY, 2, @Today);
        ///DECLARE @Day4 DATETIME = DATEADD(DAY, 3, @Today);
        ///DECLARE @Day5 DATETIME = DATEADD(DAY, 4, @Today);
        ///DECLARE @Day6 DATETIME = DATEADD(DAY, 5, @Today);
        ///DECLARE @Day7 DATETIME = DATEADD(DAY, 6, @Today);
        ///DECLARE @Day8 DATETIME = DATEADD(DAY, 7, @Today);
        ///
        ///-------------------- São Be [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Guarulhos {
            get {
                return ResourceManager.GetString("Guarulhos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- CIDADE --
        ///DECLARE @CityID INT = 8;
        ///
        ///-- DIAS --
        ///DECLARE @Today DATETIME = GETDATE();
        ///DECLARE @Day1 DATETIME = @Today;
        ///DECLARE @Day2 DATETIME = DATEADD(DAY, 1, @Today);
        ///DECLARE @Day3 DATETIME = DATEADD(DAY, 2, @Today);
        ///DECLARE @Day4 DATETIME = DATEADD(DAY, 3, @Today);
        ///DECLARE @Day5 DATETIME = DATEADD(DAY, 4, @Today);
        ///DECLARE @Day6 DATETIME = DATEADD(DAY, 5, @Today);
        ///DECLARE @Day7 DATETIME = DATEADD(DAY, 6, @Today);
        ///DECLARE @Day8 DATETIME = DATEADD(DAY, 7, @Today);
        ///
        ///-------------------- Niteró [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Niterói {
            get {
                return ResourceManager.GetString("Niterói", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- CIDADE --
        ///DECLARE @CityID INT = 9;
        ///
        ///-- DIAS --
        ///DECLARE @Today DATETIME = GETDATE();
        ///DECLARE @Day1 DATETIME = @Today;
        ///DECLARE @Day2 DATETIME = DATEADD(DAY, 1, @Today);
        ///DECLARE @Day3 DATETIME = DATEADD(DAY, 2, @Today);
        ///DECLARE @Day4 DATETIME = DATEADD(DAY, 3, @Today);
        ///DECLARE @Day5 DATETIME = DATEADD(DAY, 4, @Today);
        ///DECLARE @Day6 DATETIME = DATEADD(DAY, 5, @Today);
        ///DECLARE @Day7 DATETIME = DATEADD(DAY, 6, @Today);
        ///DECLARE @Day8 DATETIME = DATEADD(DAY, 7, @Today);
        ///
        ///-------------------- Petróp [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Petrópolis {
            get {
                return ResourceManager.GetString("Petrópolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///-- CIDADE --
        ///DECLARE @CityID INT = 1
        ///
        ///-- DIAS --
        ///DECLARE @Today DATETIME = GETDATE();
        ///DECLARE @Day1 DATETIME = @Today;
        ///DECLARE @Day2 DATETIME = DATEADD(DAY, 1, @Today);
        ///DECLARE @Day3 DATETIME = DATEADD(DAY, 2, @Today);
        ///DECLARE @Day4 DATETIME = DATEADD(DAY, 3, @Today);
        ///DECLARE @Day5 DATETIME = DATEADD(DAY, 4, @Today);
        ///DECLARE @Day6 DATETIME = DATEADD(DAY, 5, @Today);
        ///DECLARE @Day7 DATETIME = DATEADD(DAY, 6, @Today);
        ///DECLARE @Day8 DATETIME = DATEADD(DAY, 7, @Today);
        ///
        ///
        ///-------------------- POR [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Porto_Alegre {
            get {
                return ResourceManager.GetString("Porto_Alegre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///
        ////****************** RESETAR BANCO DE DADOS ******************/
        ///IF (@Reset = 1) BEGIN
        ///	DELETE [Estado]
        ///	DELETE [Cidade]
        ///	DELETE [PrevisaoClima]
        ///END
        ///
        ///
        ///
        ////****************** ADICIONAR ESTADOS *****************/
        ///
        ///-- RS --
        ///INSERT INTO [Estado] (Id, Nome, UF)
        ///VALUES (1, &apos;Rio Grande do Sul&apos;, &apos;RS&apos;);
        ///
        ///-- SP --
        ///INSERT INTO [Estado] (Id, Nome, UF)
        ///VALUES (2, &apos;São Paulo&apos;, &apos;SP&apos;);
        ///
        ///-- RJ --
        ///INSERT INTO [Estado] (Id, Nome, UF)
        ///VALUES (3, &apos;Rio de Janeiro&apos;, &apos;RJ&apos;);
        ///
        ///
        ///
        ////***************** ADICIONAR  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Preparar_Banco {
            get {
                return ResourceManager.GetString("Preparar_Banco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- CIDADE --
        ///DECLARE @CityID INT = 7;
        ///
        ///-- DIAS --
        ///DECLARE @Today DATETIME = GETDATE();
        ///DECLARE @Day1 DATETIME = @Today;
        ///DECLARE @Day2 DATETIME = DATEADD(DAY, 1, @Today);
        ///DECLARE @Day3 DATETIME = DATEADD(DAY, 2, @Today);
        ///DECLARE @Day4 DATETIME = DATEADD(DAY, 3, @Today);
        ///DECLARE @Day5 DATETIME = DATEADD(DAY, 4, @Today);
        ///DECLARE @Day6 DATETIME = DATEADD(DAY, 5, @Today);
        ///DECLARE @Day7 DATETIME = DATEADD(DAY, 6, @Today);
        ///DECLARE @Day8 DATETIME = DATEADD(DAY, 7, @Today);
        ///
        ///-------------------- Rio de [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Rio_de_Janeiro {
            get {
                return ResourceManager.GetString("Rio_de_Janeiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- CIDADE --
        ///DECLARE @CityID INT = 6;
        ///
        ///-- DIAS --
        ///DECLARE @Today DATETIME = GETDATE();
        ///DECLARE @Day1 DATETIME = @Today;
        ///DECLARE @Day2 DATETIME = DATEADD(DAY, 1, @Today);
        ///DECLARE @Day3 DATETIME = DATEADD(DAY, 2, @Today);
        ///DECLARE @Day4 DATETIME = DATEADD(DAY, 3, @Today);
        ///DECLARE @Day5 DATETIME = DATEADD(DAY, 4, @Today);
        ///DECLARE @Day6 DATETIME = DATEADD(DAY, 5, @Today);
        ///DECLARE @Day7 DATETIME = DATEADD(DAY, 6, @Today);
        ///DECLARE @Day8 DATETIME = DATEADD(DAY, 7, @Today);
        ///
        ///-------------------- Guarul [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string São_Bernardo_do_Campo {
            get {
                return ResourceManager.GetString("São_Bernardo_do_Campo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- CIDADE --
        ///DECLARE @CityID INT = 3
        ///
        ///-- DIAS --
        ///DECLARE @Today DATETIME = GETDATE();
        ///DECLARE @Day1 DATETIME = @Today;
        ///DECLARE @Day2 DATETIME = DATEADD(DAY, 1, @Today);
        ///DECLARE @Day3 DATETIME = DATEADD(DAY, 2, @Today);
        ///DECLARE @Day4 DATETIME = DATEADD(DAY, 3, @Today);
        ///DECLARE @Day5 DATETIME = DATEADD(DAY, 4, @Today);
        ///DECLARE @Day6 DATETIME = DATEADD(DAY, 5, @Today);
        ///DECLARE @Day7 DATETIME = DATEADD(DAY, 6, @Today);
        ///DECLARE @Day8 DATETIME = DATEADD(DAY, 7, @Today);
        ///
        ///-------------------- São Jos [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string São_José_dos_Ausentes {
            get {
                return ResourceManager.GetString("São_José_dos_Ausentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- CIDADE --
        ///DECLARE @CityID INT = 4
        ///
        ///-- DIAS --
        ///DECLARE @Today DATETIME = GETDATE();
        ///DECLARE @Day1 DATETIME = @Today;
        ///DECLARE @Day2 DATETIME = DATEADD(DAY, 1, @Today);
        ///DECLARE @Day3 DATETIME = DATEADD(DAY, 2, @Today);
        ///DECLARE @Day4 DATETIME = DATEADD(DAY, 3, @Today);
        ///DECLARE @Day5 DATETIME = DATEADD(DAY, 4, @Today);
        ///DECLARE @Day6 DATETIME = DATEADD(DAY, 5, @Today);
        ///DECLARE @Day7 DATETIME = DATEADD(DAY, 6, @Today);
        ///DECLARE @Day8 DATETIME = DATEADD(DAY, 7, @Today);
        ///
        ///-------------------- São Pau [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string São_Paulo {
            get {
                return ResourceManager.GetString("São_Paulo", resourceCulture);
            }
        }
    }
}
